# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interval.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(594, 467)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 581, 431))
        self.widget_2.setObjectName("widget_2")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.widget_2)
        self.lcdNumber_2.setGeometry(QtCore.QRect(360, 30, 91, 61))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget_2)
        self.lcdNumber.setGeometry(QtCore.QRect(480, 30, 91, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(370, 10, 61, 18))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(500, 10, 61, 18))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setGeometry(QtCore.QRect(453, 30, 20, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line.setFont(font)
        self.line.setLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(360, 100, 211, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setGeometry(QtCore.QRect(10, 220, 561, 191))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 557, 187))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setGeometry(QtCore.QRect(10, 10, 531, 41))
        self.widget_3.setObjectName("widget_3")
        self.spinBox = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox.setGeometry(QtCore.QRect(10, 0, 52, 41))
        self.spinBox.setObjectName("spinBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(82, 0, 271, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.timeEdit = QtWidgets.QTimeEdit(self.widget_3)
        self.timeEdit.setGeometry(QtCore.QRect(380, 1, 118, 41))
        self.timeEdit.setObjectName("timeEdit")
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setGeometry(QtCore.QRect(10, 60, 531, 41))
        self.widget_4.setObjectName("widget_4")
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_2.setGeometry(QtCore.QRect(10, 0, 52, 41))
        self.spinBox_2.setObjectName("spinBox_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(82, 0, 271, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.widget_4)
        self.timeEdit_2.setGeometry(QtCore.QRect(380, 1, 118, 41))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setGeometry(QtCore.QRect(0, 0, 531, 41))
        self.widget_5.setObjectName("widget_5")
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox_3.setGeometry(QtCore.QRect(10, 0, 52, 41))
        self.spinBox_3.setObjectName("spinBox_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(82, 0, 271, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.widget_5)
        self.timeEdit_3.setGeometry(QtCore.QRect(380, 1, 118, 41))
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_6.setGeometry(QtCore.QRect(10, 110, 531, 41))
        self.widget_6.setObjectName("widget_6")
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget_6)
        self.spinBox_4.setGeometry(QtCore.QRect(10, 0, 52, 41))
        self.spinBox_4.setObjectName("spinBox_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_5.setGeometry(QtCore.QRect(82, 0, 271, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.widget_6)
        self.timeEdit_4.setGeometry(QtCore.QRect(380, 1, 118, 41))
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_7.setGeometry(QtCore.QRect(10, 160, 531, 41))
        self.widget_7.setObjectName("widget_7")
        self.spinBox_5 = QtWidgets.QSpinBox(self.widget_7)
        self.spinBox_5.setGeometry(QtCore.QRect(10, 0, 52, 41))
        self.spinBox_5.setObjectName("spinBox_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_6.setGeometry(QtCore.QRect(82, 0, 271, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.timeEdit_5 = QtWidgets.QTimeEdit(self.widget_7)
        self.timeEdit_5.setGeometry(QtCore.QRect(380, 1, 118, 41))
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(20, 110, 291, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setGeometry(QtCore.QRect(10, 170, 561, 31))
        self.widget.setObjectName("widget")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 21, 18))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 61, 18))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(410, 10, 61, 18))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.line_2 = QtWidgets.QFrame(self.widget_2)
        self.line_2.setGeometry(QtCore.QRect(10, 140, 561, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setGeometry(QtCore.QRect(20, 30, 241, 32))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 30, 31, 34))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(80, 80, 131, 18))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(80, 10, 131, 18))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "минуты"))
        self.label_2.setText(_translate("MainWindow", "секунды"))
        self.pushButton.setText(_translate("MainWindow", "начать"))
        self.pushButton_2.setText(_translate("MainWindow", "пауза"))
        self.pushButton_3.setText(_translate("MainWindow", "сброс"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.timeEdit_3.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.timeEdit_4.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.timeEdit_5.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.label_5.setText(_translate("MainWindow", "#"))
        self.label_3.setText(_translate("MainWindow", "действие"))
        self.label_4.setText(_translate("MainWindow", "время"))
        self.pushButton_4.setText(_translate("MainWindow", "add"))
        self.label_6.setText(_translate("MainWindow", "текущая цепочка"))
        self.label_7.setText(_translate("MainWindow", "список цепочек"))

