# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/interval.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 301)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 581, 281))
        self.widget_2.setObjectName("widget_2")
        self.lcd_minute = QtWidgets.QLCDNumber(self.widget_2)
        self.lcd_minute.setGeometry(QtCore.QRect(300, 30, 121, 61))
        self.lcd_minute.setObjectName("lcd_minute")
        self.lcd_second = QtWidgets.QLCDNumber(self.widget_2)
        self.lcd_second.setGeometry(QtCore.QRect(450, 30, 111, 61))
        self.lcd_second.setObjectName("lcd_second")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(310, 10, 61, 18))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(440, 10, 61, 18))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 100, 266, 36))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.begin_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.begin_button.setObjectName("begin_button")
        self.horizontalLayout.addWidget(self.begin_button)
        self.pause_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout.addWidget(self.pause_button)
        self.reset_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.line_2 = QtWidgets.QFrame(self.widget_2)
        self.line_2.setGeometry(QtCore.QRect(10, 140, 561, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.recipe_list_box = QtWidgets.QComboBox(self.widget_2)
        self.recipe_list_box.setGeometry(QtCore.QRect(20, 30, 241, 32))
        self.recipe_list_box.setObjectName("recipe_list_box")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(80, 10, 131, 18))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(60, 180, 131, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(60, 240, 141, 18))
        self.label_4.setObjectName("label_4")
        self.cur_tomate_text = QtWidgets.QLineEdit(self.widget_2)
        self.cur_tomate_text.setEnabled(False)
        self.cur_tomate_text.setGeometry(QtCore.QRect(240, 170, 331, 32))
        self.cur_tomate_text.setObjectName("cur_tomate_text")
        self.next_tomate_text = QtWidgets.QLineEdit(self.widget_2)
        self.next_tomate_text.setEnabled(False)
        self.next_tomate_text.setGeometry(QtCore.QRect(240, 230, 331, 32))
        self.next_tomate_text.setObjectName("next_tomate_text")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setGeometry(QtCore.QRect(20, 80, 251, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_recipe_button = QtWidgets.QPushButton(self.widget)
        self.add_recipe_button.setObjectName("add_recipe_button")
        self.horizontalLayout_2.addWidget(self.add_recipe_button)
        self.change_recipe_button = QtWidgets.QPushButton(self.widget)
        self.change_recipe_button.setObjectName("change_recipe_button")
        self.horizontalLayout_2.addWidget(self.change_recipe_button)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setGeometry(QtCore.QRect(280, 10, 16, 131))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "минуты"))
        self.label_2.setText(_translate("MainWindow", "секунды"))
        self.begin_button.setText(_translate("MainWindow", "начать"))
        self.pause_button.setText(_translate("MainWindow", "пауза"))
        self.reset_button.setText(_translate("MainWindow", "сброс"))
        self.label_7.setText(_translate("MainWindow", "список рецептов"))
        self.label_3.setText(_translate("MainWindow", "Текущий томат"))
        self.label_4.setText(_translate("MainWindow", "Следующий томат"))
        self.add_recipe_button.setText(_translate("MainWindow", "новый рецепт"))
        self.change_recipe_button.setText(_translate("MainWindow", "изменить рецепт"))

