# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/interval.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 429)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 581, 401))
        self.widget_2.setObjectName("widget_2")
        self.lcd_minute = QtWidgets.QLCDNumber(self.widget_2)
        self.lcd_minute.setGeometry(QtCore.QRect(300, 30, 111, 61))
        self.lcd_minute.setObjectName("lcd_minute")
        self.lcd_second = QtWidgets.QLCDNumber(self.widget_2)
        self.lcd_second.setGeometry(QtCore.QRect(450, 30, 111, 61))
        self.lcd_second.setObjectName("lcd_second")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(310, 10, 61, 18))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(440, 10, 61, 18))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 100, 266, 36))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.begin_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.begin_button.setObjectName("begin_button")
        self.horizontalLayout.addWidget(self.begin_button)
        self.pause_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout.addWidget(self.pause_button)
        self.reset_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.line_2 = QtWidgets.QFrame(self.widget_2)
        self.line_2.setGeometry(QtCore.QRect(10, 140, 561, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.recipe_list_box = QtWidgets.QComboBox(self.widget_2)
        self.recipe_list_box.setGeometry(QtCore.QRect(20, 30, 241, 32))
        self.recipe_list_box.setObjectName("recipe_list_box")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(80, 10, 131, 18))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setGeometry(QtCore.QRect(20, 100, 251, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_recipe_button = QtWidgets.QPushButton(self.widget)
        self.add_recipe_button.setObjectName("add_recipe_button")
        self.horizontalLayout_2.addWidget(self.add_recipe_button)
        self.change_recipe_button = QtWidgets.QPushButton(self.widget)
        self.change_recipe_button.setObjectName("change_recipe_button")
        self.horizontalLayout_2.addWidget(self.change_recipe_button)
        self.button_remove_recipe = QtWidgets.QPushButton(self.widget)
        self.button_remove_recipe.setObjectName("button_remove_recipe")
        self.horizontalLayout_2.addWidget(self.button_remove_recipe)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setGeometry(QtCore.QRect(280, 10, 16, 131))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tomat_list = QtWidgets.QScrollArea(self.widget_2)
        self.tomat_list.setGeometry(QtCore.QRect(10, 210, 561, 181))
        self.tomat_list.setWidgetResizable(True)
        self.tomat_list.setObjectName("tomat_list")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 557, 177))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tomat_list.setWidget(self.scrollAreaWidgetContents)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 160, 561, 41))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.line_3 = QtWidgets.QFrame(self.widget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_4.addWidget(self.line_3)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.line_4 = QtWidgets.QFrame(self.widget_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_4.addWidget(self.line_4)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tomato Cook"))
        self.label.setText(_translate("MainWindow", "минуты"))
        self.label_2.setText(_translate("MainWindow", "секунды"))
        self.begin_button.setText(_translate("MainWindow", "начать"))
        self.pause_button.setText(_translate("MainWindow", "пауза"))
        self.reset_button.setText(_translate("MainWindow", "сброс"))
        self.label_7.setText(_translate("MainWindow", "список рецептов"))
        self.add_recipe_button.setText(_translate("MainWindow", "новый"))
        self.change_recipe_button.setText(_translate("MainWindow", "изменить"))
        self.button_remove_recipe.setText(_translate("MainWindow", "удалить"))
        self.label_3.setText(_translate("MainWindow", "Томаты"))
        self.label_4.setText(_translate("MainWindow", "Минуты"))
        self.label_5.setText(_translate("MainWindow", "Cекунды"))

